/**
 * A lightweight, streaming-friendly Markdown Parser.
 * Designed to handle incomplete syntax optimistically.
 */
export default class MarkdownParser {
  parse(text: string): string {
    if (!text) return "";

    let html = text;

    // 1. Sanitize HTML tags to prevent XSS (basic)
    html = html.replace(/</g, "&lt;").replace(/>/g, "&gt;");

    // 2. Code Blocks (```)
    // Handle closed blocks
    html = html.replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code class="language-$1">$2</code></pre>');
    // Handle open blocks at the end of the string (Optimistic)
    html = html.replace(/```(\w*)\n([\s\S]*)$/g, '<pre><code class="language-$1">$2</code></pre>');
    // Handle blocks that haven't even started content yet
    html = html.replace(/```(\w*)$/g, '<pre><code class="language-$1"></code></pre>');

    // 3. Inline Code (`)
    html = html.replace(/`([^`]+)`/g, '<code>$1</code>');
    // Optimistic inline code (unclosed at end)
    // Warning: This can be risky if standard text ends with a backtick, but useful for streaming.
    // We only match if it looks like code (no newlines)
    html = html.replace(/`([^`\n]+)$/g, '<code>$1</code>');

    // 4. Headers
    html = html.replace(/^# (.*$)/gm, '<h1>$1</h1>');
    html = html.replace(/^## (.*$)/gm, '<h2>$1</h2>');
    html = html.replace(/^### (.*$)/gm, '<h3>$1</h3>');

    // 5. Bold (** or __)
    html = html.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/__([^_]+)__/g, '<strong>$1</strong>');
    
    // 6. Italic (* or _)
    html = html.replace(/\*([^*]+)\*/g, '<em>$1</em>');
    html = html.replace(/_([^_]+)_/g, '<em>$1</em>');

    // 7. Lists (Unordered)
    // Simple transform for streaming - real lists need state to wrap in <ul>
    // Here we just style the items themselves
    html = html.replace(/^\s*-\s+(.*$)/gm, '<li class="list-disc ml-4">$1</li>');

    // 8. Paragraphs
    // Wrap text that isn't inside a tag yet
    // This is tricky with regex-only parsing.
    // We'll replace double newlines with <br/><br/> for simplicity in this demo
    html = html.replace(/\n\n/g, '<br/><br/>');
    html = html.replace(/\n/g, '<br/>');

    // Cleanup: Remove extra br inside pre/code generated by the newline replacement
    // (This is a simplified approach, a real tokenizer is better for robust parsing)
    
    return html;
  }
}
